# Generated by Django 5.0.3 on 2024-03-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=30)),
                ('eligibility', models.CharField(max_length=30)),
                ('cgpa', models.FloatField(blank=True, default=0.0)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(max_length=30)),
            ],
        ),
    ]
